#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DNR.Droid.Resource", IsApplication=true)]

namespace DNR.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int default_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dnr_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_content_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_av_pause = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_av_play = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_av_stop = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int descriptionView = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int pauseButton = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int playButton = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int podcastImage = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int podcastsListView = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int seekBar1 = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int statusText = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int stopButton = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int textView1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int textView2 = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PodcastDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PodcastItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int Hello = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int pause = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int play = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int stop = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int BaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
